main/routes.py
from flask import render_template, request, Blueprint, flash, make_response, g
from app.posts.forms import IndexcalendarForm as ChoosecalendarForm
from app.models import Post
from app.users.forms import RegistrationForm, ContactForm
from app.models import User
from app import bcrypt, db
from config import Config
# Высылка почты при регистрации мне и новому клиенту. Сохранение картинок которые добавляет новый пользователь
from app.users.utils import send_registration_request, save_request_pic
# Сохранение картинок для отправки мне на почту
from app.users.utils import save_request_forsend_pic32, save_request_forsend_pic31, save_request_forsend_residence
from datetime import datetime, timedelta

main = Blueprint('main', __name__)


# Домашняя страница
@main.route('/', methods=['POST', 'GET'])
@main.route('/home', methods=['POST', 'GET'])
def home():
    currentdate = datetime.now().strftime("%Y-%m-%d")
    mindateto = datetime.now() + timedelta(days=1)
    mindateto = mindateto.strftime("%Y-%m-%d")
    maxavailabledate = datetime.now() + timedelta(days=366)
    maxavailabledate = maxavailabledate.strftime("%Y-%m-%d")
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    form = ChoosecalendarForm()
    if form.validate_on_submit():
        receivedatefrom = form.datefrom.data
        receivedateto = form.dateto.data
        if receivedatefrom >= receivedateto:
            flash('ОШИБКА! Дата начала аренды не может быть больше даты окончания аренды!')
            return render_template('index.html', form=form, posts=posts, currentdatefrom=currentdate,         currentdateto=mindateto, maxavailabledate=maxavailabledate)
        else:
            posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
            postsx = Post.query.order_by(Post.date_posted.desc()).all()

            #Выводим список дат которые ввёл пользователь
            date_generated = [receivedatefrom + timedelta(days=x)
            for x in range(0, (receivedateto-receivedatefrom).days)]
            check_the_data = str()
            for date in date_generated:
                check_the_data += date.strftime("%Y-%m-%d,")
            print("")
            print("Нужные даты: ", check_the_data)
            print("Тип нужных дат: ", type(check_the_data))
            print("")

            # allposts - содержит в себе id's всех доступных постов
            allposts = list()
            for y in postsx:
                allposts.append(y.id)
            print("Все объявления: ", allposts )
            print("Тип всех объявлений: ", type(allposts))
            print("")

            # exclude содержит в себе id's которые нужно удалить из allposts
            readyposts = Post.query.filter(Post.notavailable.contains(check_the_data)).all()

            print("Посты, которые нельзя выводить: ", readyposts)
            print("Тип постов, которые нельзя выводить: ", type(readyposts))
            print("")

            #Посты, которые нужно вывести на экран
            result = list()
            for z in readyposts:
                print(z.id)
                result.append(z.id)
            print(result)
            toshow=list(set(allposts) ^ set(result))
            print("A toshow is: ", toshow)
            print("A type is: ", type(toshow))

            #Вывод на экран постов, которые нужно вывести на

            showme = Post.query.filter(Post.id.in_(toshow)).order_by(Post.date_posted.desc()).\
            paginate(page=page, per_page=5)
            print("XXX: ", showme)
            return render_template('index.html', form=form, posts=showme,
                               currentdatefrom=receivedatefrom,
                               currentdateto=receivedateto, currentdateset=currentdate, maxavailabledate=maxavailabledate)
    return render_template('index.html', form=form, posts=posts, currentdatefrom=currentdate,           currentdateto=mindateto, maxavailabledate=maxavailabledate)


# Админ панель владельца, доступ возможен только мне
@main.route('/god', methods=['POST', 'GET'])
def godishere():
    auth = request.authorization
    if auth and request.authorization.username == Config.GOD_USERNAME and request.authorization.password == Config.GOD_PASS:
        x = str()
        f = open('auth_list.xrpt')
        for line in f:
            x += line
        f.close()
        form = RegistrationForm()
        if form.validate_on_submit():
            hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
            user = User(username=form.username.data, email=form.email.data, password=hashed_password, name = form.name.data, surname = form.surname.data, phone = form.phone.data)
            db.session.add(user)
            db.session.commit()
            flash(f'Аккаунт создан для {form.username.data}', 'success')
            form.username.data = ""
            form.password.data = ""
            form.email.data = ""
            form.name.data = ""
            form.surname.data = ""
            form.phone.data = ""
        return render_template('god.html', form=form, x=x)
    else:
        return make_response('', 401, {'www-Authenticate': 'Basic realm = "Login Required"'})


# Разлогинивание владельца (меня)
@main.route('/godout', methods=['POST', 'GET'])
def godout():
    return make_response('', 401, {'www-Authenticate': 'Basic realm = "Login Required"'})


# Как пользоваться сайтом? (extends base.html)
@main.route('/useit')
def useit():
    return render_template('useit.html', title='Как пользоваться сайтом?')


# Как стать партнером? (extends base.html)
@main.route('/partner', methods=['POST', 'GET'])
def partner():
    form = ContactForm()
    if form.validate_on_submit():
        save_request_pic(form.cont_name.data, form.cont_surname.data, form.cont_picture32.data)
        save_request_forsend_pic32(form.cont_picture32.data)
        save_request_pic(form.cont_name.data, form.cont_surname.data, form.cont_picture31.data)
        save_request_forsend_pic31(form.cont_picture31.data)
        save_request_pic(form.cont_name.data, form.cont_surname.data, form.cont_picture_residence.data)
        save_request_forsend_residence(form.cont_picture_residence.data)
        send_registration_request(form.cont_name.data, form.cont_surname.data, form.cont_phone.data,
                                  form.cont_datas.data, form.cont_email.data)
        flash(f'Заявка успешно отправлена! Ожидайте звонка в течение 48 часов.', 'success')
        form.cont_name.data = ''
        form.cont_surname.data = ''
        form.cont_phone.data = ''
        form.cont_datas.data = ''
        form.cont_email.data = ''
        return render_template('partner.html', form=form, title='Как стать партнером?')
    else:
        return render_template('partner.html', form=form, title='Как стать партнером?')


# О компании (extends base.html)
@main.route('/about')
def about():
    return render_template('about.html', title='О кампании')

posts/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint, g)
from flask_login import current_user, login_required
from app import db
from app.models import Post, User, Vouchers
from app.posts.forms import PostForm, UpdatePostForm, UpdatePhoto1Form, UpdatePhoto2Form, UpdatePhoto3Form
from app.posts.utils import save_picture, save_picture2, save_picture3
from app.posts.forms import PostcalendarForm
from datetime import datetime, timedelta
import os
from random import randint
from app.users.utils import send_book_approval, send_book_to_lessor
from dateutil.relativedelta import relativedelta


posts = Blueprint('posts', __name__)


@posts.route('/post/new', methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        save_picture(form.photo_1.data, form.car_plate.data)
        save_picture2(form.photo_2.data, form.car_plate.data)
        save_picture3(form.photo_3.data, form.car_plate.data)
        _, f_ext1 = os.path.splitext(form.photo_1.data.filename)
        _, f_ext2 = os.path.splitext(form.photo_2.data.filename)
        _, f_ext3 = os.path.splitext(form.photo_3.data.filename)
        post = Post(car_brand=form.car_brand.data.capitalize(),
                    car_model=form.car_model.data.capitalize(),
                    car_color=form.car_color.data.capitalize(),
                    car_plate=form.car_plate.data,
                    car_creation=form.car_creation.data,
                    car_body=form.car_body.data,
                    car_fuel=form.car_fuel.data,
                    car_engine=form.car_engine.data,
                    car_drive=form.car_drive.data,
                    car_transmission=form.car_transmission.data,
                    car_insuerance=form.car_insuerance.data,
                    price=form.price.data,
                    content=form.content.data.capitalize(),
                    profilepicture=current_user.username + form.car_plate.data + f_ext1,
                    profilepicture2=current_user.username + form.car_plate.data + f_ext2,
                    profilepicture3=current_user.username + form.car_plate.data + f_ext3,
                    author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Объявление успешно размещено', 'success')
        return redirect(url_for('main.home'))
    return render_template('create_post.html', title='Новое объявление', form=form, legend='Новое объявление:')


@posts.route("/post/<int:post_id>", methods=['GET', 'POST'])
def post(post_id):
    currentdate = datetime.now().strftime("%Y-%m-%d")
    mindateto = datetime.now() + timedelta(days=1)
    mindateto = mindateto.strftime("%Y-%m-%d")
    post = Post.query.get_or_404(post_id)
    form = PostcalendarForm()
    voucherint = randint(0, 100000)
    maxavailabledate = datetime.now() + timedelta(days=366)
    maxavailabledate = maxavailabledate.strftime("%Y-%m-%d")
    sevendaysprice = int(post.price)*7
    if form.validate_on_submit():
        datefrom = form.datefrom.data
        dateto = form.dateto.data
        # Checking if the beggining date does not exceed the end date of the vaucher
        if datefrom > dateto:
            flash('ОШИБКА! Дата начала аренды не может быть больше даты окончания аренды!')
            currentdate = datetime.now().strftime("%Y-%m-%d")
            mindateto = datetime.now() + timedelta(days=1)
            mindateto = mindateto.strftime("%Y-%m-%d")
            return render_template('post.html', title=post.car_brand, post=post, form=form, currentdateset=currentdate, mindateto=mindateto, maxavailabledate=maxavailabledate, sevendaysprice=sevendaysprice)
        if dateto > datefrom:
            notavailable_data = post.notavailable
            if notavailable_data == "":
                f_date = form.datefrom.data.strftime("%Y-%m-%d")
                t_date = form.dateto.data.strftime("%Y-%m-%d")
                f_date = f_date.split('-')
                t_date = t_date.split('-')
                f_dateready = datetime(int(f_date[0]),int(f_date[1]),int(f_date[2]))
                t_dateready = datetime(int(t_date[0]),int(t_date[1]),int(t_date[2]))
                ft_date = t_dateready - f_dateready
                sum=ft_date.days
                sum_voucher=sum*int(post.price)
                dayprice = post.price
                totalprice = sum_voucher
                totaldays = sum
                client_name = form.client_name.data
                client_birth = form.client_birth.data
                client_email = form.client_email.data
                client_phone = form.client_phone.data
                booktime = str(form.exacttime.data)
                voucher_ok = Vouchers(post=post_id, voucher=voucherint, user_id=post.author.id, booktime=datetime.utcnow()+timedelta(hours=3), dayprice=dayprice, totalprice=totalprice, totaldays=totaldays, client_name=client_name, client_birth=client_birth, client_email=client_email, client_phone=client_phone, book_from=datefrom, book_to=dateto, booktimefrom_to=booktime)
                db.session.add(voucher_ok)
                db.session.commit()
                # Below was a code like: notavailable_list=list()
                notavailable_list=str()
                date_generated = [datefrom + timedelta(days=x)
                for x in range(0, (dateto-datefrom).days)]
                for date in date_generated:
                    # Below wos code like: notavailable_list.append(date.strftime("%Y-%m-%d"))
                    notavailable_list += (date.strftime("%Y-%m-%d,"))
                # Below was a code like: notavailable_list += str(dateto)+","
                post.notavailable=notavailable_list
                db.session.commit()
                # The code below sends emails and renders checkout template
                send_book_approval(voucherint, post.author.name, post.author.surname, post.author.email, post.author.phone, post.car_brand, post.car_engine, post.car_transmission, post.car_fuel, client_name, client_birth, client_email, client_phone, dayprice, totalprice, datefrom, dateto, booktime, post.car_model, sum)
                send_book_to_lessor(voucherint, post.author.name, post.author.surname, post.author.email, post.author.phone, post.car_brand, post.car_engine, post.car_transmission, post.car_fuel, client_name, client_birth, client_email, client_phone, dayprice, totalprice, datefrom, dateto, booktime, post.car_model, post.car_plate, post.id, sum, post.author.id)
                return render_template('checkout.html', title='Бронь подтверждена!', form=form, post=post, voucherint=voucherint, sum_voucher=sum_voucher, maxavailabledate=maxavailabledate, sevendaysprice=sevendaysprice)
            else:
                # Здесь нужно сделать проерку на совпадение параметра post.notavailable
                f_date = form.datefrom.data.strftime("%Y-%m-%d")
                t_date = form.dateto.data.strftime("%Y-%m-%d")
                f_date = f_date.split('-')
                t_date = t_date.split('-')
                f_dateready = datetime(int(f_date[0]),int(f_date[1]),int(f_date[2]))
                t_dateready = datetime(int(t_date[0]),int(t_date[1]),int(t_date[2]))
                ft_date = t_dateready - f_dateready
                sum=ft_date.days
                date_generated = [datefrom + timedelta(days=x)
                for x in range(0, (dateto-datefrom).days)]
                check_the_data = list()
                for date in date_generated:
                    check_the_data.append(date.strftime("%Y-%m-%d"))
                #Checking if dates are already taken
                a = check_the_data
                b = post.notavailable.split(',')
                result=list(set(a) & set(b))
                if result:
                    flash('ОШИБКА! На выбранные даты машина уже забронирована!')
                    currentdate = datetime.now().strftime("%Y-%m-%d")
                    mindateto = datetime.now() + timedelta(days=1)
                    mindateto = mindateto.strftime("%Y-%m-%d")
                    return render_template('post.html', title=post.car_brand, post=post, form=form, currentdateset=currentdate, mindateto=mindateto, maxavailabledate=maxavailabledate, sevendaysprice=sevendaysprice)
                else:
                    alldates = b.append(a)
                    sum_voucher=sum*int(post.price)
                    dayprice = post.price
                    totalprice = sum_voucher
                    totaldays = sum
                    client_name = form.client_name.data
                    client_birth = form.client_birth.data
                    client_email = form.client_email.data
                    client_phone = form.client_phone.data
                    booktime = str(form.exacttime.data)
                    voucher_ok = Vouchers(post=post_id, voucher=voucherint, user_id=post.author.id, booktime=datetime.utcnow()+timedelta(hours=3), dayprice=dayprice, totalprice=totalprice, totaldays=totaldays, client_name=client_name, client_birth=client_birth, client_email=client_email, client_phone=client_phone, book_from=datefrom, book_to=dateto, booktimefrom_to=booktime)
                    db.session.add(voucher_ok)
                    db.session.commit()
                    # Below was a code like: notavailable_list=list()
                    notavailable_list=str(notavailable_data)
                    date_generated = [datefrom + timedelta(days=x)
                    for x in range(0, (dateto-datefrom).days)]
                    for date in date_generated:
                        # Below wos code like: notavailable_list.append(date.strftime("%Y-%m-%d"))
                        notavailable_list += (date.strftime("%Y-%m-%d,"))
                    # Below was a code like: notavailable_list += str(dateto)+","
                    post.notavailable=notavailable_list
                    db.session.commit()

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="https://fonts.googleapis.com/css?
family=Montserrat:400,900&display=swap&subset=cyrillic,cyrillic-ext" rel="stylesheet">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<link rel="stylesheet" href="{{ url_for('static', filename='minecss/basestyle.css') }}">
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='minecss/justinaguilar.css') }}">
  {% if title %}
   <title>{{ title }}</title>
  {% else %}
   <title>Belavtorent</title>
  {% endif %}
</head>
  <body>
    <header class="site-header mb-6">
      <nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top">
          <a class="navbar-brand mr-5" href="/">RentAvtoBy</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{ url_for('main.useit')}}">Как пользоваться сайтом?</a>
              <a class="nav-item nav-link" href="{{ url_for('main.about')}}">О компании</a>
              <a class="nav-item nav-link" href="{{ url_for('main.partner')}}">Как стать партнером?</a>
            </div>
            <!-- Правая сторона навигации -->
            {% if current_user.is_authenticated %}
            <div class="navbar-nav text">
              <a class="nav-item nav-link" href="{{ url_for('users.adminlogged')}}">Аккаунт</a>
              <a class="nav-item nav-link btn-outline-danger" href="{{ url_for('users.logout')}}">Выйти из системы</a>
            </div>
            {% endif %}
        </div>
      </nav>
    </header>
  <article class="card">
  {% block content %}
  <!-- Зесь отображается основная инфа
       Текст вносить в файл about.html-->
  {% endblock %}
  </article>
  <footer class="card">
    <div class="row justify-content-between">
      <div class="col ">
        <address>Республика Беларусь. г.Брест</address><br>
      </div>
      <div class="col-6">
        <div id="worktime">По всем вопросам:<br>Пон-ПТ: 9:00 - 18:00<br></div><br>
      </div>
      <div class="col border-left light">
        ИП Климук Василий Владимирович<br> Тел: +375336024442<br> yndac@protonmail.com
      </div>
    </div>
  </footer>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

templates/index.html
{% extends "indexlayout.html" %}
{% block content %}
{% for post in posts.items %}
<!-- Пост -->
<div class="row">
<article class="media content-section shadow-lg">
    <a href="{{ url_for('posts.post', post_id=post.id) }}"><img title="Подробное описание" alt="Здесь должно быть изображение авто" class="align-self-center mr-4 indeximg nohoverimg rounded" src="{{ url_for('static', filename='profile pictures/'+post.profilepicture ) }}"></a>
  <div class="media-body">
     <div class="article-metadata">
       {% if post.author == current_user %}
        <a class="mr-2" href="{{url_for('users.user_posts', username=post.author.username)}}">{{post.author.username }}</a>
        {% else %}
          <a class="mr-2" href="" title="Имя автора">{{post.author.username }}</a>
       {% endif %}
      <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
     </div>
    <h1><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.car_brand }} {{ post.car_model }}</a></h1>
    <p class="col-sm-6 article-content">
      <div class="row pl-4">
        <h4>
        <span class="btn btn-warning mb-2">
          {{ post.car_fuel }}
        </span>
        <span class="btn btn-success mb-2">
          {{ post.car_transmission }}
        </span>
        <span class="btn btn-warning mb-2">
          {{ post.car_engine }} Л.
        </span>
        <span class="btn btn-warning mb-2">
          {{ post.car_insuerance }}
        </span>
        </h4>
      </div>
    </p>
    <div class="alert alert-success">
      <article style="text-align:center;">Стоимость за сутки: {{ post.price }} РУб.</article>
    </div>
    <div class="row">
      <div class="col-sm-12">
        <a title="Забронировать этот автомобиль" href="{{ url_for('posts.post', post_id=post.id) }}"><button type="button" class="btn btn-primary mx-3 mb-3 mt-0">Перейти к бронированию</button></a>
      </div>
    </div>
  </div>
</article>
</div>
{% endfor %}
{% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
  {% if page_num %}
   {% if posts.page == page_num %}
    <a class="btn btn-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
   {% else %}
    <a class="btn btn-outline-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
   {% endif %}
  {% else %}
   ...
  {% endif %}
{% endfor %}
{% endblock content %}

templates/indexlayout.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="https://fonts.googleapis.com/css?
family=Montserrat:400,900&display=swap&subset=cyrillic,cyrillic-ext" rel="stylesheet">
  <!-- Bootstrap Стили -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <!--Мои стили-->
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='minecss/indexstyle.css') }}">
  <!--Стили с сайта http://www.justinaguilar.com-->
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='minecss/justinaguilar.css') }}">
{% if title %}
 <title>{{ title }}</title>
{% else %}
 <title>Главная страница</title>
{% endif %}
<!-- Календарь -->
</head>
<body>
<header class="site-header">
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top">
      <a class="navbar-brand mr-5" href="/">RentAvtoBy</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarToggle">
        <div class="navbar-nav mr-auto">
          <a class="nav-item nav-link" href="{{ url_for('main.useit')}}">Как пользоваться сайтом?</a>
          <a class="nav-item nav-link" href="{{ url_for('main.about')}}">О компании</a>
          <a class="nav-item nav-link" href="{{ url_for('main.partner')}}">Как стать партнером?</a>
        </div>
        <!-- Правая сторона навигации -->
        {% if current_user.is_authenticated %}
        <div class="navbar-nav">
          <a class="nav-item nav-link" href="{{ url_for('users.adminlogged')}}">Аккаунт</a>
          <a class="nav-item nav-link btn-outline-danger" href="{{ url_for('users.logout')}}">Выйти из системы</a>
        </div>
        {% endif %}
    </div>
  </nav>
</header>
  <main role="main" class="container">
      <br>
    <button class="btn btn-success btn-lg mb-2 calendarbutton" type="button" data-toggle="collapse" data-target=".multi-collapse" aria-expanded="false" aria-controls="datefrom dateto">Выбрать дату аренды</button>
    <form target= "_self" method="post">
      {{ form.hidden_tag() }}
      <div class="container-fluid mx-0 my-0 px-0 py-0">
        <div class="row justify-content-center px-sm-0">
            <!-- Выбор даты начала аренды -->
            <div class="col-sm-4 mb-2 mx-sm-0">
              <div class="collapse multi-collapse" id="datefrom">
                <div class="card">
                      <p class="calenaralign">Дата начала аренды:
                        {{ form.datefrom (class="fromdate", value=currentdatefrom, min=currentdateset, max=maxavailabledate) }}
                </div>
              </div>
            </div>
            <!-- Выбор даты окончания аренды -->
            <div class="col-sm-4 mb-2">
              <div class="collapse multi-collapse" id="dateto">
                <div class="card">
                    <p class="calenaralign">Дата окончания аренды:
                      {{ form.dateto (class="fromdate", value=currentdateto, min=currentdateto, max=maxavailabledate) }}
                </div>
              </div>
            </div>

            <div class="col-xs-12 col-2 align-self-center">
              <div class="collapse multi-collapse" id="multiCollapseExample2">
                <button type="submit" class="btn btn-success btn-lg">Найти доступные автомобили</button>
              </div>
            </div>

        </div>
    </div>
  </form>
      <div class="row">
        <div class="container-fluid col-sm-8">
          <!-- Панель информации -->
            {% with messages = get_flashed_messages (with_categories=true) %}
              {% if messages %}
                {% for category, message in messages %}
                  <div class = "alert alert-danger  fade-show" style="text-align: center; height: 35px;">
                    <strong>{{ message }}</strong>
                      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&#10004;</span>
                      </button>
                  </div>
                {% endfor %}
              {% endif %}
            {% endwith %}
          {% block content %}
          <!-- Здесь отображаются все посты -->
          {% endblock %}
        </div>
        <div class="container-fluid col-sm-2">

        </div>
      </div>
    </main>
    <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</body>
</html>